version: "3.8"

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gpt-trivia-metadata-db
    user: postgres

volumes:
  db-data: