-- Deploy metadata-db:appschema to pg

BEGIN;

CREATE TYPE "reaction_type" AS ENUM (
  'like',
  'dislike',
  'custom'
);

CREATE TYPE "role_type" AS ENUM (
  'standard',
  'admin'
);

CREATE TABLE "follows" (
  "following_user_id" integer,
  "followed_user_id" integer,
  "created_at" timestamp WITHOUT TIME ZONE DEFAULT (now())
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar UNIQUE,
  "password" varchar,
  "email" varchar UNIQUE,
  "birth_date" timestamp,
  "role" role_type,
  "created_at" timestamp WITHOUT TIME ZONE DEFAULT (now())
);

CREATE TABLE "friend_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_requester_id" integer,
  "user_requested_id" integer,
  "accepted" bool DEFAULT false,
  "rejected" bool DEFAULT false,
  "created_at" timestamp WITHOUT TIME ZONE DEFAULT (now()),
  "updated_at" timestamp WITHOUT TIME ZONE
);

CREATE TABLE "friends" (
  "user_id_1" integer,
  "user_id_2" integer
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar,
  "body" text,
  "user_id" integer,
  "status" varchar,
  "created_at" timestamp WITHOUT TIME ZONE DEFAULT (now()),
  "edited_at" timestamp WITHOUT TIME ZONE
);

CREATE TABLE "reactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer,
  "post_id" integer,
  "type" reaction_type
);

CREATE TABLE "player_pools" (
  "id" UUID NOT NULL,
  "user_id" integer NOT NULL,
  "match_id" UUID
);

CREATE TABLE "matches" (
  "id" UUID PRIMARY KEY NOT NULL,
  "started_at" timestamp WITHOUT TIME ZONE DEFAULT (now()),
  "finished_at" timestamp WITHOUT TIME ZONE,
  "match_data" jsonb
);

CREATE TABLE "match_questions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "subcategory_id" integer,
  "question" text,
  "answer" integer,
  "choice_1" text,
  "choice_2" text,
  "choice_3" text,
  "choice_4" text
);

CREATE TABLE "match_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer,
  "name" text NOT NULL
);

CREATE TABLE "match_subcategories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "category_id" integer,
  "name" text NOT NULL
);

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("following_user_id") REFERENCES "users" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("followed_user_id") REFERENCES "users" ("id");

ALTER TABLE "player_pools" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "reactions" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "reactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "player_pools" ADD FOREIGN KEY ("match_id") REFERENCES "matches" ("id") ON DELETE CASCADE;

ALTER TABLE "match_questions" ADD FOREIGN KEY ("subcategory_id") REFERENCES "match_subcategories" ("id") ON DELETE CASCADE;

ALTER TABLE "match_subcategories" ADD FOREIGN KEY ("category_id") REFERENCES "match_categories" ("id") ON DELETE CASCADE;

ALTER TABLE "match_categories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "friend_requests" ADD FOREIGN KEY ("user_requester_id") REFERENCES "users" ("id");

ALTER TABLE "friend_requests" ADD FOREIGN KEY ("user_requested_id") REFERENCES "users" ("id");

ALTER TABLE "friends" ADD FOREIGN KEY ("user_id_1") REFERENCES "users" ("id");

ALTER TABLE "friends" ADD FOREIGN KEY ("user_id_2") REFERENCES "users" ("id");

-- Indexes for columns
CREATE UNIQUE INDEX users_username_idx ON users (LOWER(username));

CREATE UNIQUE INDEX users_email_dx ON users (LOWER(email));

CREATE INDEX friends_user_id_1_idx ON friends (user_id_1);

CREATE INDEX friends_user_id_2_idx ON friends (user_id_2);

CREATE INDEX follows_following_user_id_idx ON follows (following_user_id);

CREATE INDEX follows_followed_user_id_idx ON follows (followed_user_id);

CREATE INDEX posts_user_id_idx ON posts (user_id);

CREATE INDEX reactions_user_id_idx ON reactions (user_id);

CREATE INDEX reactions_post_id_idx ON reactions (post_id);

CREATE INDEX match_questions_subcategory_id_idx ON match_questions (subcategory_id);

CREATE UNIQUE INDEX match_categories_name_idx ON match_categories (LOWER(name));

CREATE UNIQUE INDEX match_subcategories_name_idx ON match_subcategories (category_id, LOWER(name));

CREATE INDEX match_subcategories_category_id_idx ON match_subcategories (category_id);

CREATE INDEX player_pool_match_id_idx ON player_pools (match_id);

CREATE INDEX player_pools_user_id_idx ON player_pools (user_id);

CREATE UNIQUE INDEX friends_userid1_userid2_idx on friends (user_id_1, user_id_2);

CREATE UNIQUE INDEX friend_requests_user_requester_id_user_requested_id_idx on friend_requests (user_requester_id, user_requested_id);

COMMIT;
