-- Deploy metadata-db:appschema to pg

BEGIN;

CREATE TYPE "reaction_type" AS ENUM (
  'like',
  'dislike',
  'custom'
);

CREATE TYPE "role_type" AS ENUM (
  'standard',
  'admin'
);

CREATE TABLE "follows" (
  "following_user_id" integer,
  "followed_user_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "users" (
  "id" integer PRIMARY KEY NOT NULL,
  "username" varchar UNIQUE,
  "password" varchar,
  "email" varchar UNIQUE,
  "birth_date" timestamp,
  "role" role_type,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "friend_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "friend_user_requester" integer,
  "friend_user_requested" integer,
  "accepted" bool,
  "rejected" bool,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "friends" (
  "user_id_1" integer,
  "user_id_2" integer
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar,
  "body" text,
  "user_id" integer,
  "status" varchar,
  "created_at" timestamp DEFAULT (now()),
  "edited_at" timestamp
);

CREATE TABLE "reactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer,
  "post_id" integer,
  "type" reaction_type
);

CREATE TABLE "player_pools" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer
);

CREATE TABLE "matches" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "player_pool_id" integer,
  "started_at" timestamp DEFAULT (now()),
  "finished_at" timestamp
);

CREATE TABLE "match_questions" (
  "match_id" integer,
  "question" text,
  "answer" text
);

CREATE TABLE "match_histories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "match_id" integer,
  "match_data" jsonb
);

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("following_user_id") REFERENCES "users" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("followed_user_id") REFERENCES "users" ("id");

ALTER TABLE "player_pools" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "reactions" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "reactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "matches" ADD FOREIGN KEY ("player_pool_id") REFERENCES "player_pools" ("id");

ALTER TABLE "match_questions" ADD FOREIGN KEY ("match_id") REFERENCES "matches" ("id");

ALTER TABLE "match_histories" ADD FOREIGN KEY ("match_id") REFERENCES "matches" ("id");

ALTER TABLE "friend_requests" ADD FOREIGN KEY ("friend_user_requester") REFERENCES "users" ("id");

ALTER TABLE "friend_requests" ADD FOREIGN KEY ("friend_user_requested") REFERENCES "users" ("id");

ALTER TABLE "friends" ADD FOREIGN KEY ("user_id_1") REFERENCES "users" ("id");

ALTER TABLE "friends" ADD FOREIGN KEY ("user_id_2") REFERENCES "users" ("id");

-- Indexes for columns
CREATE UNIQUE INDEX users_username_idx ON users (LOWER(username));

CREATE UNIQUE INDEX users_email_dx ON users (LOWER(email));

CREATE INDEX friends_user_id_1_idx ON friends (user_id_1);

CREATE INDEX friends_user_id_2_idx ON friends (user_id_2);

CREATE INDEX follows_following_user_id_idx ON follows (following_user_id);

CREATE INDEX follows_followed_user_id_idx ON follows (followed_user_id);

CREATE INDEX posts_user_id_idx ON posts (user_id);

CREATE INDEX reactions_user_id_idx ON reactions (user_id);

CREATE INDEX reactions_post_id_idx ON reactions (post_id);

CREATE INDEX match_histories_match_id_idx ON match_histories (match_id);

CREATE INDEX match_questions_match_id_idx ON match_questions (match_id);

CREATE INDEX match_player_pool_id_idx ON matches (player_pool_id);

CREATE INDEX player_pools_user_id_idx ON player_pools (user_id);

COMMIT;
